### ISSUE TITLE
Error in average.py script

### ISSUE THREAD

**Issue by thomasdebeus** [stekhn/average-faces-opencv#2]
Hi Steffen!

I'm not a python user and a beginner programmer in R so I wonder if you could help me with a few errors. I have downloaded my own images and successfully created the `.txt` files with the `extract.py` script.

Now I'm at the final stage of creating the average face with the `average.py` script only it runs into an error when run the `python average.py data/images 170 240` command:

```
  File "average.py", line 136
    print file_path
                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(file_path)?
```

When I change `print file_path` into `print(file_path)` in the code I get the following error:

```
Traceback (most recent call last):
  File "average.py", line 301, in <module>
    main()
  File "average.py", line 65, in main
    for i in xrange(0, num_images):
NameError: name 'xrange' is not defined
```

I'm a journalist at the Dutch newspaper de Volkskrant and I wanted to test your scripts on the photo's from our parliament. Help is much appreciated!

**Comment by stekhn** [comment]
Hi Thomas,

I added the missing parenthesis to make the code more compatible with newer versions Python.

See commit f856ab111453fc337cd5e67360c528daea8a8f3e

Hope I could help!
